name: Daily Birthday Check

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM daily

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Replace with your desired version
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run birthday check script
        run: |
          python mail_tool/your_script.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
